// Generated by gencpp from file node_communication/person.msg
// DO NOT EDIT!


#ifndef NODE_COMMUNICATION_MESSAGE_PERSON_H
#define NODE_COMMUNICATION_MESSAGE_PERSON_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace node_communication
{
template <class ContainerAllocator>
struct person_
{
  typedef person_<ContainerAllocator> Type;

  person_()
    : a(0)
    , b(0)
    , sum(0)  {
    }
  person_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , sum(0)  {
  (void)_alloc;
    }



   typedef uint8_t _a_type;
  _a_type a;

   typedef uint8_t _b_type;
  _b_type b;

   typedef uint8_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::node_communication::person_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::node_communication::person_<ContainerAllocator> const> ConstPtr;

}; // struct person_

typedef ::node_communication::person_<std::allocator<void> > person;

typedef boost::shared_ptr< ::node_communication::person > personPtr;
typedef boost::shared_ptr< ::node_communication::person const> personConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::node_communication::person_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::node_communication::person_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::node_communication::person_<ContainerAllocator1> & lhs, const ::node_communication::person_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::node_communication::person_<ContainerAllocator1> & lhs, const ::node_communication::person_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace node_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::node_communication::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::node_communication::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_communication::person_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::node_communication::person_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_communication::person_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::node_communication::person_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::node_communication::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f32a6e30f428448f61ee5e7099ed0bd";
  }

  static const char* value(const ::node_communication::person_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f32a6e30f428448ULL;
  static const uint64_t static_value2 = 0xf61ee5e7099ed0bdULL;
};

template<class ContainerAllocator>
struct DataType< ::node_communication::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "node_communication/person";
  }

  static const char* value(const ::node_communication::person_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::node_communication::person_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 a\n"
"uint8 b\n"
"uint8 sum\n"
;
  }

  static const char* value(const ::node_communication::person_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::node_communication::person_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct person_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::node_communication::person_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::node_communication::person_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b);
    s << indent << "sum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NODE_COMMUNICATION_MESSAGE_PERSON_H
